### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by pbvahlst** [hoijui/JavaOSC#4]
Hi there, nice little API :-)

It has some concurrency issues though which needs attention, I will be happy to give some pointers if the project is still active. E.g.

OSCPacketDispatcher:
You need to use a ConcurrentHashMap for this to be thread safe, if you where to add a listener after OSCPortIn has started receiving messages there could be visibility issues of the newly added listener and ConcurrentModificationExceptions could occur 

OSCMessage:
is not Immutable and therefore not thread safe. This can cause issues with visibility when crossing thread boundaries 

OSCPortIn:
The listening flag will be accessed by multiple threads and is not currently thread safe. Should be changed to volatile or accessed In thread safe manner. If not this could cause visibility issues and in worst case it will never stop running because it want see the state change of the listening flag.

.... More issues....

**Comment by Burtan** [comment]
I think there is one more threading problem. When you send data one OSCSerializer is built per sending operation, as it is not thread safe, but they all share the buffer from the OSCPortOut.

**Comment by DiMoSe** [comment]
I'm consistently getting an error when receiving values quickly. I figure it's not hard to avoid, I really don't need to receive the instructions that quickly but thought it related to this thread. If you need any more info I can provide to help fix this let me know, it's quite easy to reproduce. 
```
Exception in thread "Thread-1" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.illposed.osc.OSCPacketDispatcher.dispatchMessageNow(OSCPacketDispatcher.java:401)
	at com.illposed.osc.OSCPacketDispatcher.dispatchPacket(OSCPacketDispatcher.java:287)
	at com.illposed.osc.OSCPacketDispatcher.handlePacket(OSCPacketDispatcher.java:300)
	at com.illposed.osc.transport.OSCPortIn.run(OSCPortIn.java:199)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
