### ISSUE TITLE
when adding `com.illposed.osc:javaosc-java-se-addons` all other handlers are no longer registered

### ISSUE THREAD

**Issue by NikkyAI** [hoijui/JavaOSC#74]
```
com.illposed.osc.OSCSerializeException: No type handler registered for serializing class java.lang.String
	at com.illposed.osc.OSCSerializer.findSuperType(OSCSerializer.java:371) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.OSCSerializer.findType(OSCSerializer.java:384) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.OSCSerializer.findType(OSCSerializer.java:395) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.OSCSerializer.write(OSCSerializer.java:414) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.OSCSerializer.writeAddress(OSCSerializer.java:229) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.OSCSerializer.write(OSCSerializer.java:247) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.OSCSerializer.writePacket(OSCSerializer.java:281) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.OSCSerializer.write(OSCSerializer.java:293) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.transport.channel.OSCDatagramChannel.send(OSCDatagramChannel.java:98) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.transport.udp.UDPTransport.send(UDPTransport.java:134) ~[javaosc-core-0.9.jar:na]
	at com.illposed.osc.transport.OSCPortOut.send(OSCPortOut.java:119) ~[javaosc-core-0.9.jar:na]
```

it seems that the `com.illposed.osc:javaosc-java-se-addons` artifact overrides `com.illposed.osc.argument.handler.Activator` and only registers the `r` `com.illposed.osc.argument.handler.AwtColorArgumentHandler`

in case it helps..

```
java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-58)
OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)
```

to patch this temporarily in my codebase i had to make copies of `OSCPortInBuilder` and `OSCPortOutBuilder` that allow setting the `serializerBuilder`

PS: i only added the dependency to make the debug logging shut up about Classloader errors and unavailable serializers,

would be useful to have this mentioned on the README too.. the only info i found about it was in some old issue: https://github.com/hoijui/JavaOSC/issues/60#issuecomment-981498939

**Comment by hoijui** [comment]
Thanks for the report, and sorry for the long wait. I did not get any notifications :/
I think I addressed all your issues:

- moved the java-se stuff to a different package (should take care of the overloading/overwriting issue)
- mentioned the dependency to add in the error message you got

Sorry for the troubles!
