### ISSUE TITLE
Is there somewhere a working Android example ?

### ISSUE THREAD

**Issue by hannesa2** [hoijui/JavaOSC#77]
I'm fighting with Android and run into multiple issues, so the general question arise: 
Is there somewhere a running sample for Android ?

**Comment by hannesa2** [comment]
When I use it
`implementation "com.illposed.osc:javaosc-core:0.9"`

```
android {
   ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}
```
It runs into
```
java.lang.NoSuchMethodError: No virtual method getDefinedPackage(Ljava/lang/String;)Ljava/lang/Package; in class Ljava/lang/ClassLoader; 
or its super classes (declaration of 'java.lang.ClassLoader' appears in /apex/com.android.art/javalib/core-oj.jar)
  at com.illposed.osc.LibraryInfo.<clinit>(LibraryInfo.java:46)
  at com.illposed.osc.LibraryInfo.hasStandardProtocolFamily(LibraryInfo.java:283)
  at com.illposed.osc.transport.udp.UDPTransport.<init>(UDPTransport.java:61)
  at com.illposed.osc.transport.OSCPort.<init>(OSCPort.java:40)
  at com.illposed.osc.transport.OSCPortIn.<init>(OSCPortIn.java:108)
  at com.illposed.osc.transport.OSCPortIn.<init>(OSCPortIn.java:123)
  at com.illposed.osc.transport.OSCPortIn.<init>(OSCPortIn.java:132)
  at com.illposed.osc.transport.OSCPortIn.<init>(OSCPortIn.java:145)
  at com.illposed.osc.transport.OSCPortIn.<init>(OSCPortIn.java:160)
  at com.illposed.osc.transport.OSCPortIn.<init>(OSCPortIn.java:170)
```

**Comment by youlisse** [comment]
https://github.com/youlisse/Ircam

check that its only osc send from android in kotlin but might help

**Comment by hannesa2** [comment]
Thanks for the hints. I've to receive in Android from outside the device and I've issues to receive something. Maybe it's an network ?

**Comment by youlisse** [comment]
if you think it could be the network and you dont have the hand on it try with your phone as an hotspot some network block udp message (like public network, company network ...)

**Comment by youlisse** [comment]
i struggle also implement osc in :(

**Comment by hannesa2** [comment]
> https://github.com/youlisse/Ircam
> 
> check that its only osc send from android in kotlin but might help

Your repo is disappeared @youlisse 
<img width="654" alt="Image" src="https://github.com/user-attachments/assets/2fa6d490-3b74-4d65-bcef-27fe67a6ac8b" />

**Comment by cormacstewart14** [comment]
@hannesa2 did you ever find a solution? I am trying to stand up an Android project using this library as well and have run in the the exact same issues that you described above.

**Comment by hannesa2** [comment]
@cormacstewart14 Unfortunately no, I assume its an UDP issue. At least some google issues are pointing to this.
In my point of view an Android sample is missing here which tests it.
My current state is this https://github.com/hannesa2/OSC-android-server but till now I failed

**Comment by cormacstewart14** [comment]
@hannesa2 thanks for the reply... I think forking the repo could get it working but that isn't ideal

**Comment by hannesa2** [comment]
What would be the ideal working situation, how can I help ?

**Comment by Daniel8bits** [comment]
The problem is that the core module is using relying on some packages that does not exist on Android, so when you try to run it, Android complains. In version 0.8 it says specifically that the classloader could not load java.awt.Color, and in version 0.9 it is complaining about getDefinedPackage from classloader that apparently does not exist in Android either.

The following image shows where specifically the error comes from on core (line 46):

![Image](https://github.com/user-attachments/assets/75e1047c-9fba-47f2-a498-535d3210e96b)

The error is happening inside a static block during the loading of some packages.
